version: "3.3"
services:
  shortener:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    links:
      - postgres
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
