openapi: 3.0.3
info:
  description : "API shortener"
  title: Shortener
  version: 1.0.0
  contact:
    name: Mikhail Belov
    url: mailto:formatmyc@gmail.com
paths:
  /{shortURL}:
    get:
      summary: Forward from short URL to long URL
      description: This endpoint forwarding from short URL to long URL.
      operationId: forwardURL
      parameters:
        - name: shortURL
          in: path
          description: "Required. Short URL."
          required: true
          schema:
            type: string
            format: uri
      responses:
        '307':
          description: The request was redirected
          content:
            application/json:
              schema:
                type: string
                format: uri
  /shrot/{longURL}:
    get:
      summary: Return short URL
      description: This endpoint returns short URL from long URL.
      operationId: getShortURL
      parameters:
        - name: longURL
          in: path
          description: "Required. Long URL."
          required: true
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: The request was successful
          content:
            application/json:
              schema:
                type: string
                format: uri
  /stat/{shortURL}:
    get:
      summary: Return statistics for short URL
      description: This endpoint returns statistics for short URL.
      operationId: getStat
      parameters:
        - name: shortURL
          in: path
          description: "Required. Short URL."
          required: true
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: The request was successful
          content:
            application/json:
              schema:
                type: integer
                format: int64
